# Generated by Django 2.2.4 on 2019-08-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='codigo',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('pregunta', 'codigo'), name='codigo_unico'),
        ),
    ]
