# Generated by Django 2.2.4 on 2019-08-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20190831_1145'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pregunta',
            constraint=models.UniqueConstraint(fields=('encuesta', 'codigo'), name='codigo_unico'),
        ),
    ]
