# Generated by Django 2.2.4 on 2019-08-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_auto_20190831_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='codigo',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
