# Generated by Django 2.2.4 on 2019-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_auto_20190831_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
