# Generated by Django 2.2.4 on 2019-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_respuesta_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
