# Generated by Django 2.2.4 on 2019-08-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0007_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='cod_pregunta',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='cod_respuesta',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
